Switch license to GPLv3 because of crates.io limitation
When trying to publish this crate, cargo publish fails with:

error: api errors: unknown license or other term: GPL-3.0-or-later; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers

Seems like an issue with their SPDX identifier list?